type User @table {
  username: String!
  email: String!
  avatarUrl: String
  bio: String
}

type Project @table {
  title: String!
  createdAt: Timestamp!
  owner: User!
  description: String
  deadline: Date
}

type Task @table {
  title: String!
  status: String!
  project: Project!
  assignee: User
  description: String
  dueDate: Date
}

type ProjectMember @table {
  project: Project!
  user: User!
  role: String!
}

type Comment @table {
  content: String!
  task: Task!
  author: User!
  createdAt: Timestamp!
}